### ISSUE TITLE
Fix xfdesktop file operations

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#1]
Using this version of Thunar, xfdesktop files operations (e.g. Create folder, delete file...) stop working.

Steps to reproduce:
* pkill Thunar
* Start thunar compiled from source
* Try to create a folder or file on desktop

Nothing happens. I noticed that /usr/bin/thunar was launching as daemon in background, but if I remove the GTK2 Thunar and install this version the daemon won't launch even using --daemon, just the lt-thunar --daemon process, but not Thunar --daemon as in GTK2.

This problem affects xfdesktop 4.12.3 and the current GTK3 development branch.

**Comment by Skunnyk** [comment]
When adding a folder, a dbus call is sent, but no answer.

> method call time=1493644147.642342 sender=:1.16 -> destination=org.xfce.FileManager serial=71 path=/org/xfce/FileManager; interface=org.xfce.FileManager; member=CreateFile
>    string "file:///home/skunnyk/Desktop"
>    string "inode/directory"
>    string ":0.0"
>    string "_TIME138546419"

I think it's related to thunarx / xfdesktop+thunar integration.

**Comment by andreldm** [comment]
Taking a look at this, I discovered that Thunar has to expose two services, org.xfce.FileManager and org.xfce.Thunar. The trouble is that only latter is registered here:
https://github.com/andreldm/thunar/blob/gtk3/thunar/thunar-application.c#L1001

If I change "org.xfce.Thunar" by "org.xfce.FileManager" and restart xfdesktop things work nicely again.
This "switch" is also noticed while using D-Feet.
Well, I really don't know how to solve this using GApplication, it's like having two targets to hit with only one bullet.
