### ISSUE TITLE
No icons shown on files for "icon view" and "compact list view"

### ISSUE THREAD

**Issue by alexxcons** [andreldm/thunar#11]
view --> view as icons 
view --> view as compact

both do not show icons on the files

**Comment by alexxcons** [comment]
I started have look for this one, however I will be off for some days now.

**Comment by alexxcons** [comment]
Till now I only found out, that commenting out "cairo_paint_with_alpha (cr, alpha);" in thunar-icon-renderer.c:471 leads to the same effect for DetailedListView.
Loading the icons seems to work fine as far as I can see. It seems to be a render-issue.

Edit: However cairo does not report any problems:

const char * test_status_string = cairo_status_to_string (cairo_status (cr));
printf("cairo status: %s\n", test_status_string);

Result: cairo status: no error has occurred

**Comment by alexxcons** [comment]
This could be relevant:
"thunar_standard_view_draw" ( base of all views) is called frequently on cursor move, where "thunar_abstract_icon_view_draw" ( base of icon and compact view ) seems to be not called at all.

Edit: Is not relevant --> Same behaviour in thunar-gtk2 .. and there icons work fine.

**Comment by andreldm** [comment]
Random hint: View as Icons and View as Compact List use ExoIconView whereas View as Detailed List uses ExoTreeView.

**Comment by alexxcons** [comment]
ok, thanks! .. currently I just dont have time to further debug :( Please dont hesitate to take the issue, if I am too slow!

**Comment by cron-job** [comment]
.. to be checked if there is some other thread which un-paints the items at some point.

**Comment by andreldm** [comment]
Handled in #19
