### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#13]
Hotkeys such as Ctrl+c & Ctrl+v don't work anymore. Everything else works, rename(F2), delete(Del), Go back and forward (Alt Left & Right)...

**Comment by frapa** [comment]
I made a pull request [here](https://github.com/andreldm/thunar/pull/16).

I solved by adding these 3 shortcuts to the menu items. I am not sure if there is some custom binding somewhere else, but it now seems to be working properly. Maybe the shortcuts were lost in the porting?

**Comment by andreldm** [comment]
Probably, pull request merged.
