### ISSUE TITLE
Thunar crashes while restoring file from trash

### ISSUE THREAD

**Issue by frapa** [andreldm/thunar#15]
Steps to reproduce the issue:

1. Open Thunar go to Trash.
2. Try to restore file or folder.
3. Thunar crashes but the file is restored.

**Comment by frapa** [comment]
I think this is a symptom of a widespread bug that leads Thunar to crashes. It seems to be due to a memory access error.

**Comment by frapa** [comment]
I think it's the same as this one https://github.com/andreldm/thunar/issues/12

In that case the list of operations which trigger the bug is to be updated.

**Comment by andreldm** [comment]
Yes, it also crashes on thunar_thumbnail_cache_copy_async_reply.
#12 updated, thanks for looking into this.
