### ISSUE TITLE
Scrollbars shouldn't start faded

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#21]
In some folders, only in Icons and Compact view modes, the scrollbars start faded (edge-overshot event of GTK3).

![screenshot](https://cloud.githubusercontent.com/assets/599565/26064288/e280db7e-3966-11e7-811b-094565fdb4c9.png)

**Comment by andreldm** [comment]
Even now that I'm using Arc instead of Numix this problem is present, always reproducible in my Downloads folder, even though the files are completely different.

It's also reproducible if one creates a folder and puts a screenshot there (i.g. Screenshot_2017-06-14_00-09-20.png):

![screenshot_2017-06-14_00-10-37](https://user-images.githubusercontent.com/599565/27113850-ef5cd0f0-5095-11e7-878e-f4836f47ccc6.png)

**Comment by alexxcons** [comment]
It looks like there are 3 fading states "fully faded", if mouse is outside the widget. "Minimal scrollbar visible" if mouse is inside widget and "full scrollbar visible". If mouse is on scrollbar.
Do you have the same ?

So we always want "full scrollbar visible" ? Or just "Minimal scrollbar visible" as well outside of widget ?

**Comment by andreldm** [comment]
Ideally the fade should only be visible on scrolling and reaching the bottom/top. None of these states seems to accomplish the desired result. Where did you find the docs for them?
This issue probably arises from glitches on the (already complex) layout. As a last resort, we could disable it with something like this: `.overshoot { background: transparent; border:none; }` (untested).

**Comment by alexxcons** [comment]
No, these states are just just what I can observer ( so it looks like you have a different behavior )  .. I'll just attach some screenshots.
**Mouse out of widget** ( no scrollbar )
![outofwidget](https://user-images.githubusercontent.com/2205293/28846747-e1dba076-770c-11e7-95f1-f6444c8e1930.png)
**Mouse inside the widget** ( scrollbar fades out after 2 sec if no mouse movement )
![inwidget](https://user-images.githubusercontent.com/2205293/28846759-e8d01b50-770c-11e7-855d-920b7577c3a4.png)
**Mouse on slider**
![onslider](https://user-images.githubusercontent.com/2205293/28846757-e634a992-770c-11e7-87b5-e987f7124db1.png)

But maybe I just did not find a proper folder to reproduce so far.
EDIT: Ok, I can reproduce the problem by putting a screenshot in an empty folder ( Should have tried that in the very beginning :F )

**Comment by andreldm** [comment]
Sorry, I didn't see this comment before. Yes, just create an empty folder and move some file to it. Funny that `touch file` from a terminal won't make the fade appear.

**Comment by andreldm** [comment]
Moved to [Thunar's Known Issues](https://wiki.xfce.org/releng/4.14/roadmap/thunar)
