### ISSUE TITLE
Compact List spacing

### ISSUE THREAD

**Issue by flocculant** [andreldm/thunar#24]
Spacing on folder items is greater in gtk3 - using space for no real reason.
An existing folder with 28 items (shown in 1 column) now spans 2 columns.

![gtk2](https://cloud.githubusercontent.com/assets/16842846/26211696/053cfda6-3beb-11e7-8905-67620c09874b.png)
![gtk3](https://cloud.githubusercontent.com/assets/16842846/26211695/053ae5ac-3beb-11e7-95f4-e0586883abb8.png)

**Comment by alexxcons** [comment]
The problem seems to come from [this call](https://github.com/andreldm/thunar/blob/ea5b609913bacef8ff0fd8b3a00a2c897d60fd62/thunar/thunar-compact-view.c#L60-L63)
The style-property "row-spacing" seems not to be overwritten, like the comment stats.

**Comment by andreldm** [comment]
This one should have been easy. ExoIconView has a property called `row-spacing` which defaults to 6 and can be easily changed using GtkInspector. However it's not so straightforward to set this value, in `thunar_compact_view_init` the following code has no effect:

    exo_icon_view_set_row_spacing (EXO_ICON_VIEW (gtk_bin_get_child (GTK_BIN (compact_view))), 0);

But if I use this snippet in a callback for `realize` signal, it works 😕.
If think that's too hacky, the other properties from ExoIconView are set easily in `thunar_compact_view_init` expect this one.

**Comment by alexxcons** [comment]
Not sure if `ExoIconView` should be involved here, even if it fixes the problem. As far as I can say, the approach until now was to set a style-property in `thunar-compact-view`(link above) which is read out in thunar-abstract-icon-view:
https://github.com/andreldm/thunar/blob/ea5b609913bacef8ff0fd8b3a00a2c897d60fd62/thunar/thunar-abstract-icon-view.c#L260
If I just put a "0" for `row_spacing` in `thunar_abstract_icon_view_style_set` directly, things are fixed. So for me it looks like the set of the style-property in `thunar-compact-view` does not work any more. I am currently about to try to set the prop via a `gtk_css_provider` ( that's the gtk3 way, the current stuff is deprecated ) to see if it fixes the problem but I am not finished yet .. maybe this evening.

**Comment by andreldm** [comment]
Great, fixing this via css should be better than messing with ExoIconView, the latter can be the last resort solution. If you come to prepare a pull request, please don't forget to remove gtk2-styling code.

**Comment by alexxcons** [comment]
Ok, was simpler than I first thought ... after messing around with different css approaches, I realized that it is already sufficient to install the style-property ... pull request incoming.

**Comment by andreldm** [comment]
Better yet, push your commit ;)

**Comment by alexxcons** [comment]
sorry, some fiddeling with different local git branches :roll_eyes: ... now the pull-request is ready

**Comment by alexxcons** [comment]
There is another `gtk_rc_parse_string(" ...` which I could probably replace with `gtk_widget_class_install_style_property` in [thunar-statusbar.c](https://github.com/andreldm/thunar/blob/90059d8278a13c6a6969e1b3cf605b8fd5ab4adb/thunar/thunar-statusbar.c#L93-L97)  ... I just have to figure out how to do so for enums.

... should I add it to this pull-request ?

**Comment by andreldm** [comment]
Please add to the pull request. I also asked to fix the indentation, then we can squash the commits into one.

**Comment by alexxcons** [comment]
Ok, fixed. . I re-used `g_param_spec_int` for thunar-statusbar.c, since `g_param_spec_enum` refuses to work ( no idea which type I should insert for `GType enum_type` other than the Enum-Type to get it compiled )
It seems to make no difference for the statusbar ... even if I comment out the whole block, the bar looks the same.

**Comment by andreldm** [comment]
Fixed in #28
