### ISSUE TITLE
Fix styling issues

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#29]
Currently there a few styling issues to deal with:

- Statusbar is too tall
ThunarStatusbar has margin-top and margin-bottom set to 6px, change them to 0;

- Places sidebar has no border
Easy to fix with css:
```
.sidebar.frame {
  border-style: solid;
  margin-right: 1px;
}
```

- Location toolbar is too tall
The problem are the back and forward icons, playing with GtkInspector I wasn't able to make them smaller, actually setting their icon-size to 2 makes them way too small.

**Comment by alexxcons** [comment]
Just took as well a try with GtkInspector. I agree on the smaller statusbar.
However I actually like the borderless places-sidebar. When bordered, imho thunar looks like a dual-pane file-manager.
Like it is currently, it is more clear that the left side is not just "some opened folder".

**Comment by andreldm** [comment]
@alexxcons alternatively .frame { border: 0; } make the icon view less cluttered.

**Comment by alexxcons** [comment]
@andreldm Yes, .frame { border: 0; } is better from my POV.

I currently try to set the bg-color of the places-sidebar to the same color than the  menuBar and toolBar, but I cannot figure out how to do that.

`.sidebar {  background-color: #110a91; }`
This, and as well some variations seem not to change anything.

**Comment by andreldm** [comment]
`.sidebar { background-color: #110a91; }` works here, but I don't know if it's a good idea, this should be theme-wise, a predefined value might be problematic especially when using dark[er] themes.

**Comment by alexxcons** [comment]
You are right. Probably better to leave the current bg-color.

**Comment by andreldm** [comment]
I really didn't like the sidebar completely without borders, but I would like to make them as thin as possible. Let's handle this in #32.
