### ISSUE TITLE
Fix GTK3 Deprecations

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#3]
Fix GTK3 deprecations such as: GtkTable, GtkVbox/GtkHbox, Gdk Threading and maybe GtkUIManager.
Not really urgent since we're safe to use them on GTK3, but can be a problem when we need to migrate to GTK4.

**Comment by andreldm** [comment]
A little bit of stats based on a9afb24:

    make clean && make 2> build.log
    grep "warning:" build.log | wc -l
    1336

    grep "warning:" build.log | cut -d: -f5 | sort | uniq -c | sort -n -r
    173  ‘gtk_table_get_type’ is deprecated [-Wdeprecated-declarations]
    135  ‘gtk_table_attach’ is deprecated
     83  ‘gtk_action_get_type’ is deprecated [-Wdeprecated-declarations]
     75  ‘gtk_misc_get_type’ is deprecated [-Wdeprecated-declarations]
     70  ‘gtk_misc_set_alignment’ is deprecated [-Wdeprecated-declarations]
     59  ‘gtk_action_group_get_action’ is deprecated [-Wdeprecated-declarations]
     58  ‘gtk_action_get_name’ is deprecated [-Wdeprecated-declarations]
     28  ‘gtk_action_set_visible’ is deprecated [-Wdeprecated-declarations]
     26  ‘gtk_hbox_new’ is deprecated
     25  ‘gtk_action_set_sensitive’ is deprecated [-Wdeprecated-declarations]
     22  ‘gtk_toggle_action_get_type’ is deprecated [-Wdeprecated-declarations]
     22  ‘gdk_threads_leave’ is deprecated [-Wdeprecated-declarations]
     22  ‘gdk_threads_enter’ is deprecated [-Wdeprecated-declarations]
     19  ‘gtk_table_new’ is deprecated
     17  ‘gtk_ui_manager_add_ui’ is deprecated [-Wdeprecated-declarations]
     17  ‘gtk_table_set_col_spacings’ is deprecated
     16  ‘gtk_vbox_new’ is deprecated
     16  ‘gtk_table_set_row_spacings’ is deprecated
     15  ‘gtk_ui_manager_remove_ui’ is deprecated [-Wdeprecated-declarations]
     15  ‘gtk_toggle_action_set_active’ is deprecated [-Wdeprecated-declarations]
     13  ‘gtk_action_activate’ is deprecated [-Wdeprecated-declarations]
     12  ‘gtk_ui_manager_ensure_update’ is deprecated [-Wdeprecated-declarations]
     12  ‘gtk_image_menu_item_new_with_mnemonic’ is deprecated
     10  ‘gtk_action_group_new’ is deprecated [-Wdeprecated-declarations]
     10  ‘gtk_action_create_menu_item’ is deprecated [-Wdeprecated-declarations]
      9  ‘gtk_ui_manager_insert_action_group’ is deprecated [-Wdeprecated-declarations]
      9  ‘gtk_toggle_action_get_active’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_widget_modify_text’ is deprecated
      8  ‘gtk_widget_modify_base’ is deprecated
      8  ‘gtk_vbox_get_type’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_ui_manager_remove_action_group’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_ui_manager_new_merge_id’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_radio_action_get_type’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_action_new’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_action_group_add_action_with_accel’ is deprecated [-Wdeprecated-declarations]
      8  ‘gtk_action_group_add_actions’ is deprecated [-Wdeprecated-declarations]
      7  ‘gtk_ui_manager_add_ui_from_string’ is deprecated [-Wdeprecated-declarations]
      7  ‘gtk_image_menu_item_set_image’ is deprecated [-Wdeprecated-declarations]
      7  ‘gtk_image_menu_item_get_type’ is deprecated
      7  ‘gtk_alignment_get_type’ is deprecated [-Wdeprecated-declarations]
      7  ‘gtk_action_group_add_action’ is deprecated [-Wdeprecated-declarations]
      6  ‘gtk_widget_get_style’ is deprecated
      6  ‘gtk_ui_manager_get_widget’ is deprecated [-Wdeprecated-declarations]
      6  ‘gtk_ui_manager_get_action’ is deprecated [-Wdeprecated-declarations]
      6  ‘gtk_action_group_set_translation_domain’ is deprecated [-Wdeprecated-declarations]
      6  ‘gdk_color_parse’ is deprecated
      5  label ‘out’ defined but not used [-Wunused-label]
      5  ‘gtk_misc_set_padding’ is deprecated [-Wdeprecated-declarations]
      5  ‘gtk_action_set_gicon’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_ui_manager_get_type’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_radio_action_set_current_value’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_image_new_from_stock’ is deprecated
      4  ‘gtk_icon_info_free’ is deprecated
      4  ‘gtk_alignment_new’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_action_group_remove_action’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_action_group_get_type’ is deprecated [-Wdeprecated-declarations]
      4  ‘gtk_action_get_accel_path’ is deprecated [-Wdeprecated-declarations]
      3  unused variable ‘image’ [-Wunused-variable]
      3  ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
      3  ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_radio_action_set_group’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_radio_action_new’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_radio_action_get_group’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_radio_action_get_current_value’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_image_menu_item_new_with_label’ is deprecated
      3  ‘gtk_hbox_get_type’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_action_set_tooltip’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_action_set_icon_name’ is deprecated [-Wdeprecated-declarations]
      3  ‘gtk_action_get_visible’ is deprecated [-Wdeprecated-declarations]
      3  ‘gdk_screen_make_display_name’ is deprecated [-Wdeprecated-declarations]
      3  ‘gdk_app_launch_context_new’ is deprecated
      2  unused variable ‘lp’ [-Wunused-variable]
      2  ‘return’ with no value, in function returning non-void
      2  ‘gtk_widget_reparent’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_widget_modify_style’ is deprecated
      2  ‘gtk_ui_manager_new’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_ui_manager_get_accel_group’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_tree_view_set_rules_hint’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_table_set_row_spacing’ is deprecated
      2  ‘gtk_rc_style_new’ is deprecated
      2  ‘gtk_menu_popup’ is deprecated
      2  ‘gtk_icon_source_new’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_icon_source_free’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_icon_factory_new’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_icon_factory_add_default’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_drag_begin’ is deprecated
      2  ‘gtk_dialog_set_alternative_button_order’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_dialog_get_action_area’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_button_set_focus_on_click’ is deprecated
      2  ‘gtk_action_group_list_actions’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_action_group_add_radio_actions’ is deprecated [-Wdeprecated-declarations]
      2  ‘gtk_action_get_icon_name’ is deprecated [-Wdeprecated-declarations]
      2  ‘gdk_window_get_pointer’ is deprecated
      2  ‘gdk_screen_get_monitor_geometry’ is deprecated
      2  ‘gdk_screen_get_monitor_at_point’ is deprecated
      2  ‘gdk_display_get_screen’ is deprecated [-Wdeprecated-declarations]
      2  ‘gdk_display_get_n_screens’ is deprecated [-Wdeprecated-declarations]
      1  variable ‘context’ set but not used [-Wunused-but-set-variable]
      1  variable ‘border_width’ set but not used [-Wunused-but-set-variable]
      1  unused variable ‘width’ [-Wunused-variable]
      1  unused variable ‘size’ [-Wunused-variable]
      1  unused variable ‘settings’ [-Wunused-variable]
      1  unused variable ‘selected_file’ [-Wunused-variable]
      1  unused variable ‘list’ [-Wunused-variable]
      1  unused variable ‘job’ [-Wunused-variable]
      1  unused variable ‘icon’ [-Wunused-variable]
      1  unused variable ‘height’ [-Wunused-variable]
      1  unused variable ‘error’ [-Wunused-variable]
      1  unused variable ‘dialog’ [-Wunused-variable]
      1  unused variable ‘context’ [-Wunused-variable]
      1  unused variable ‘button’ [-Wunused-variable]
      1  unused variable ‘application’ [-Wunused-variable]
      1  unused variable ‘action’ [-Wunused-variable]
      1  ‘thunar_thumbnailer_queue_async’ declared ‘static’ but never defined [-Wunused-function]
      1  ‘thunar_application_window_destroyed’ declared ‘static’ but never defined [-Wunused-function]
      1  pointer targets in passing argument 2 of ‘thunar_thumbnailer_dbus_call_queue_finish’ differ in signedness [-Wpointer-sign]
      1  passing argument 1 of ‘gtk_widget_class_install_style_property’ from incompatible pointer type [-Wincompatible-pointer-types]
      1  no previous declaration for ‘thunar_thumbnailer_begin_job’ [-Wmissing-declarations]
      1  nested extern declaration of ‘gdk_x11_set_sm_client_id’ [-Wnested-externs]
      1  implicit declaration of function ‘gdk_x11_set_sm_client_id’; did you mean ‘gtk_box_set_spacing’? [-Wimplicit-function-declaration]
      1  ‘gtk_widget_push_composite_child’ is deprecated
      1  ‘gtk_widget_pop_composite_child’ is deprecated
      1  ‘gtk_widget_get_state’ is deprecated
      1  ‘gtk_ui_manager_get_action_groups’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_tree_view_get_vadjustment’ is deprecated
      1  ‘gtk_style_render_icon’ is deprecated
      1  ‘gtk_style_lookup_icon_set’ is deprecated
      1  ‘gtk_status_icon_set_visible’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_status_icon_set_tooltip_text’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_status_icon_new_from_icon_name’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_show_uri’ is deprecated
      1  ‘gtk_paint_shadow’ is deprecated
      1  ‘gtk_menu_item_set_right_justified’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_source_set_size_wildcarded’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_source_set_size’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_source_set_pixbuf’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_source_set_icon_name’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_set_unref’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_set_render_icon’ is deprecated
      1  ‘gtk_icon_set_new’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_set_add_source’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_info_get_display_name’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_factory_remove_default’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_icon_factory_add’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_hseparator_new’ is deprecated
      1  ‘gtk_hscale_new_with_range’ is deprecated
      1  ‘gtk_hpaned_new’ is deprecated
      1  ‘gtk_alignment_set_padding’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_alignment_set’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_activatable_get_type’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_activatable_get_related_action’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_set_stock_id’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_set_label’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_is_sensitive’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_group_set_accel_group’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_group_add_toggle_actions’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_get_tooltip’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_get_sensitive’ is deprecated [-Wdeprecated-declarations]
      1  ‘gtk_action_get_proxies’ is deprecated [-Wdeprecated-declarations]
      1  ‘g_mem_is_system_malloc’ is deprecated [-Wdeprecated-declarations]
      1  ‘gdk_screen_get_number’ is deprecated [-Wdeprecated-declarations]
      1  ‘gdk_screen_get_n_monitors’ is deprecated
      1  ‘gdk_screen_get_monitor_plug_name’ is deprecated
      1  ‘gdk_pixbuf_new_from_inline’ is deprecated [-Wdeprecated-declarations]
      1  ‘gdk_cursor_unref’ is deprecated
      1  ‘gdk_cursor_new’ is deprecated [-Wdeprecated-declarations]
      1  ‘gdk_cairo_set_source_color’ is deprecated

**Comment by andreldm** [comment]
I recommend working on one type of deprecation at a time and one per commit.

**Comment by vc-01** [comment]
I will make a work-in-progress PR soon to show what deprecations i'm working on, to avoid duplicity work, unfortunately this **will** be huge patch because if _.ui_ files are rewritten, so all related gtk actions are (will touch only menus for now).

**Comment by andreldm** [comment]
Deprecations reported in Thunar's [roadmap](https://wiki.xfce.org/releng/4.14/roadmap/thunar/deprecations).
