### ISSUE TITLE
Rewrite menus to GtkBuilder format

### ISSUE THREAD

**Issue by vc-01** [andreldm/thunar#36]
To solve _some_ deprecation warnings (see issue #3) Thunar menus should be rewritten to new format for GtkBuilder as a parser.

After reading some discussion on irc dev channel, it is accepted to use `GtkImageMenuItem` for now (though deprecated) to make menus include icons.

Refactoring in future to some `XfceImageMenuItem` should be then easy by (first implementing and ...) renaming `GtkImageMenuItem` to `XfceImageMenuItem`.

(no icons in menus is not the xfce way imo ..)

**Comment by vc-01** [comment]
(i'm assigning myself to this ...)

**Comment by andreldm** [comment]
Let's handle this in #39
