### ISSUE TITLE
Investigate --gapplication-service behavior

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#37]
This option was introduced in f34f421, but it's not a replacement for --daemon.

#### --daemon behavior
* `thunar --daemon`
* open a new Thunar window
* close this window
* the deamon keeps running

#### --gapplication-service behavior
* `thunar --gapplication-service`
* open a new Thunar window
* close this window
* the process is finished

The [documentation](https://developer.gnome.org/gio/stable/GApplication.html) is not clear, so what's the use of this option?

**Comment by alexxcons** [comment]
It seems like the argument "gapplication-service" is the default-way to handle D-Bus activation in a GApplication. In the file org.xfce.Thunar.service.in it looks like the argument is passed to thunar by default:
```
[D-BUS Service]
Name=org.xfce.Thunar
Exec=@bindir@/Thunar --gapplication-service
```
.. same in org.xfce.FileManager.service.in

Here the mechanics are further described:
https://wiki.gnome.org/HowDoI/DBusApplicationLaunching
Specially the paragraph "GApplication details" provides some clarification.

However I dont know why the process finishes after passing "--gapplication-service" to thunar "by hand"

**Comment by andreldm** [comment]
I was considering to close this issue, but the following behavior worries me:
- run `thunar --daemon`
- run `thunar --gapplication-service`
- you get: `Failed to register: Unable to acquire bus name 'org.xfce.Thunar'`

Even tough strange, it's not so bad because invoking Thunar via dbus, e.g. with D-Feet calling `Launch` method of `org.xfce.FileManager` or `org.xfce.Thunar` works fine, using the running daemon instance.

**Comment by andreldm** [comment]
Moved to [Thunar's Known Issues](https://wiki.xfce.org/releng/4.14/roadmap/thunar)
