### ISSUE TITLE
Replace places sidebar with GtkPlacesSidebar?

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#4]
Evaluate if it is worth to replace this component.

**Comment by frapa** [comment]
I think for the moment it would be good to concentrate the efforts (with the little manpower we have) on making Thunar usable.

**Comment by andreldm** [comment]
Hmmm, it seems that Jonas has already done the job in e114704.
GtkInspector reports ThunarShortcutsPane->GtkPlacesSidebar, so it seems like ThunarShortcutsPane is only a wrapper.

**Comment by andreldm** [comment]
Does anyone know if it's possible to make GtkPlacesSidebar use the icon theme? That's the only downside so far to me.

**Comment by andreldm** [comment]
GtkPlacesSidebar uses symbolics icons:
https://github.com/GNOME/gtk/blob/master/gtk/gtkplacessidebar.c#L242
So, not a programming issue, but theme-wise setting.
