### ISSUE TITLE
Device mounting spinner takes too much space

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#40]
The picture says it all:
![image](https://user-images.githubusercontent.com/599565/27480824-2517d1fc-57f0-11e7-8259-af7d7cb61476.png)

**Comment by andreldm** [comment]
The trouble seems to come from [here](https://github.com/andreldm/thunar/blob/gtk3/thunar/thunar-shortcuts-view.c#L353) and [here](https://github.com/andreldm/thunar/blob/gtk3/thunar/thunar-shortcuts-view.c#L363), the `expand` parameter is set to `FALSE` in both cases, but the spinner and unmount icon are expanding nevertheless:

![image](https://user-images.githubusercontent.com/599565/27651682-8ddbf74a-5c0f-11e7-9868-3de7f207770b.png)

**Comment by andreldm** [comment]
It seems like the last renderer takes extra space even if it's not meant to expand. I have appended a text renderer and the result still doesn't make sense:
![screenshot_2017-07-10_20-17-36](https://user-images.githubusercontent.com/599565/28044343-3126e65c-65ad-11e7-8b6d-2dc31c8a55c9.png)
![screenshot_2017-07-10_20-17-51](https://user-images.githubusercontent.com/599565/28044346-3306da36-65ad-11e7-933b-6bcb3f2fa122.png)

It takes more space than it needs and doesn't shrink. Move the actual text renderer to the end and the Foo text renderer will behave as expected:
![screenshot_2017-07-10_20-22-10](https://user-images.githubusercontent.com/599565/28044387-875d4db8-65ad-11e7-8c9f-602161442ed6.png)

Diff for the mock renderer and cell backgrounds: https://gist.github.com/andreldm/50da0abddf24d3e1f80c6edc2077077c

**Comment by ochosi** [comment]
The main difference I see between Thunar's example and the appearance dialog (https://git.xfce.org/xfce/xfce4-settings/tree/dialogs/appearance-settings/main.c#n1101) is that the expanding column is not the first one in appearance, while it is in Thunar.

As you describe, when the expanding column is not the first in Thunar, it behaves as expected (which explains - at least to me - why it works in appearance settings).

I would suggest you pack your stuff into a tiny reproducer and submit an upstream bugreport against gtktreeview.

**Comment by andreldm** [comment]
After lots of time investigating, I was able to put together a SSCCE:
https://gist.github.com/andreldm/121d82b831a432e93956ef6a89e16e22

![image](https://user-images.githubusercontent.com/599565/28099462-1b80a9dc-6693-11e7-8390-9f5e5227de49.png)

The problem is related to category header, remove them and the last renderer will behave as expected:

![image](https://user-images.githubusercontent.com/599565/28099475-2bfcbada-6693-11e7-86d9-a8f07f63ef03.png)

**Comment by andreldm** [comment]
Just for the record, GtkPlacesSidebar uses [GtkListBox](https://developer.gnome.org/gtk3/stable/GtkListBox.html) instead of GtkTreeView. Switching to this widget is not really straighfoward, it would require rewriting most of Thunar's shortcuts pane.

**Comment by andreldm** [comment]
[Gist](https://gist.github.com/andreldm/121d82b831a432e93956ef6a89e16e22) updated to allow compilation against GTK2. Confirmed behavior change between GTK versions.

### GTK2
![image](https://user-images.githubusercontent.com/599565/28132553-8d1ad934-6713-11e7-8a02-198cd6d59ff9.png)

### GTK3
![image](https://user-images.githubusercontent.com/599565/28132562-978d0afe-6713-11e7-9c76-d47b47190007.png)

**Comment by ochosi** [comment]
Using GtkListBox is a possible alternative. As you said it would mean a rewrite of much of the existing code though, but it's in part much simpler than handling a treeview. Ofc some concepts like iterating the items in the listbox remain similar.

You can check xfce4-notifyd's settings dialog for an example of handling a little more complex setups with GtkListBox.
The main topic there is performance, since you'll be generating a lot of widgets. At the same time I'm not sure that amount of widgets is really problematic. But still, it's a backdraw to keep in mind.

From everything you've collected so far I would suggest you submit a bug upstream against GtkTreeview.

**Comment by andreldm** [comment]
Upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=785278

**Comment by andreldm** [comment]
Issue added to Roadmap's Known Issues.
To summarize we need on of these:
- An answer from upstream bug (already asked on irc, no response either)
- Rewrite the side pane with GtkListBox (not that easy)
- "un-revert" to GtkPlacesSidebar (has rough edges too)

**Comment by andreldm** [comment]
I was able to fix this issue by using a new column just for the spinner/eject button.
Here is the updated SSCCE: https://gist.github.com/andreldm/0f2e45882a33b67b59b13547f2d60c5f

**Comment by andreldm** [comment]
Another fix is to add the header renderer with `gtk_tree_view_column_pack_end` (gtk 3.24.12).
