### ISSUE TITLE
Implement gdbus handlers

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#41]
Implement missing handlers of g_bus_own_name introduced in:
https://github.com/andreldm/thunar/commit/7aeacea44bad881536178568346fa3b81008b7ce

**Comment by andreldm** [comment]
References:
https://git.xfce.org/xfce/xfce4-panel/commit/?id=81af574435bd3d04d395a19e8db3e059111481d2
https://git.xfce.org/xfce/xfce4-panel/commit/?id=9bc565c9a30fee9a3bf595c735d19e671ab195a5
https://git.xfce.org/xfce/xfconf/tree/xfconfd/main.c#n235

**Comment by alexxcons** [comment]
fixed in #43
