### ISSUE TITLE
Pathbar buttons visibility issues

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#46]
This script might be useful:
https://gist.github.com/andreldm/99c87f55421586d2a24c94469336c597

Open a couple of nested folders and try to increase/decrease Thunar's window width. Sometimes the filler button (the one with the edit icon) will be so small that its icon won't be visible:
![image](https://user-images.githubusercontent.com/599565/28933800-e4e3a3b0-7854-11e7-8f82-a02867613913.png)

If the windows is small enough (not really that small), the pathbar is completely hidden:
![image](https://user-images.githubusercontent.com/599565/28933911-52023038-7855-11e7-90f5-470ed83a1b23.png)

I think that `thunar_location_buttons_size_allocate` is responsible for button sizes.

**Comment by alexxcons** [comment]
As well the terminal is flooded with warning while making the window real small:
```
...
(thunar:4459): Gtk-WARNING **: Allocating size to GtkButton 0x56477e60ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(thunar:4459): Gtk-WARNING **: Negative content width -8 (allocation 2, extents 5x5) while allocating gadget (node button, owner GtkButton)

(thunar:4459): Gtk-WARNING **: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node image, owner GtkImage)

(thunar:4459): Gtk-WARNING **: Allocating size to GtkButton 0x56477e60ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
(thunar:4459): Gtk-WARNING **: Allocating size to GtkButton 0x56477e60ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(thunar:4459): Gtk-WARNING **: Negative content width -8 (allocation 2, extents 5x5) while allocating gadget (node button, owner GtkButton)

(thunar:4459): Gtk-WARNING **: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node image, owner GtkImage)

(thunar:4459): Gtk-WARNING **: Allocating size to GtkButton 0x56477e60ef80 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
... and so on
```

**Comment by andreldm** [comment]
Yes, this is the most annoying WARN ever, I tried lots of things to solve one of those in appfinder without success 😞

**Comment by alexxcons** [comment]
Think I will refactor thunar_location_buttons_size_allocate .. currently it is hard to read. Already saw some things which could be expressed in a better way / with less if/else.
Desired behavior:
- always show at least the icon of the filler widget
- always show something. Dont let the whole widget disappear.

**Comment by andreldm** [comment]
Moved to [Thunar's Known Issues](https://wiki.xfce.org/releng/4.14/roadmap/thunar)
