### ISSUE TITLE
Avoid crashes with old extensions

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#5]
As mentioned by Jonas:
Since the move to GTK3 breaks the ABI, extensions should at least be loaded from another directory to avoid crashes when old extensions are present.

**Comment by Skunnyk** [comment]
That's why we need to create a thunarx-3 for extensions, to force them to be rebuilt again gtk3 thunar. xfdesktop is already waiting for thunarx-3 : https://git.xfce.org/xfce/xfdesktop/commit/?id=af75acd3ff83274d04b69e050cb659e81396c6ac

**Comment by andreldm** [comment]
First step taken: 4abcb9a

**Comment by andreldm** [comment]
I've ported the archive plugin:
https://github.com/andreldm/thunar-archive-plugin

It's working fine here, just let me know if there's something wrong, otherwise I'll close this bug soon.

**Comment by andreldm** [comment]
Well, nothing to do here after the libthunarx version bump.
