### ISSUE TITLE
Crash on right-click --> rename

### ISSUE THREAD

**Issue by alexxcons** [andreldm/thunar#7]
Reproducable by renaming some existing file via the right-click menu. The renaming itself works, but directly afterwards thunar crashes.

The following glib critical is shown before segfault:
GLib-GIO-CRITICAL **: g_dbus_proxy_call_finish_internal: assertion 'error == NULL || *error == NULL' failed

**Comment by andreldm** [comment]
Confirmed, also happens with F2 hotkey to rename.

**Comment by andreldm** [comment]
Closing in favor of #12
