### ISSUE TITLE
Crash on right-click --> send to --> desktop

### ISSUE THREAD

**Issue by alexxcons** [andreldm/thunar#8]
Reproducable by right-click  --> send to --> desktop on some file. The creation of the link works, but directly afterwards thunar crashes.

The following glib critical is shown before segfault:
GLib-GIO-CRITICAL **: g_dbus_proxy_call_finish_internal: assertion 'error == NULL || *error == NULL' failed

Probably related to issue 7 ( crash on rename), same message and similar behaviour

**Comment by andreldm** [comment]
Closing in favor of #12
